apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenhouse-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: greenhouse
  replicas: 2
  template:
    metadata:
      labels:
        app: greenhouse
    spec:
      containers:
        - name: greenhouse
          image: raniawachene/greenhouse:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: greenhouse-ssvc
  namespace: webapps
spec:
  selector:
    app: greenhouse
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
