# PersistentVolume for MySQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql


---

# PersistentVolumeClaim for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: webapps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


---

# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: webapps
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root  # Replace with your desired root password
            - name: MYSQL_DATABASE
              value: greenhouse
            - name: MYSQL_USER
              value: greenhouse_user
            - name: MYSQL_PASSWORD
              value: root  # Replace with your desired password


---

# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: webapps
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306



---

# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenhouse-deployment
  namespace: webapps
  labels:
    app: greenhouse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greenhouse
  template:
    metadata:
      labels:
        app: greenhouse
    spec:
      containers:
        - name: greenhouse
          image: raniawachene/greenhouse:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/greenhouse"
            - name: SPRING_DATASOURCE_USERNAME
              value: "greenhouse_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"


---

# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: greenhouse-service
  namespace: webapps
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: greenhouse
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

