apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenhouse-deployment
spec:
  selector:
    matchLabels:
      app: greenhouse
  replicas: 2
  template:
    metadata:
      labels:
        app: greenhouse
    spec:
      containers:
        - name: greenhouse
          image: raniawachene/greenhouse:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # Change as needed for your environment
            - name: DB_HOST
              value: "mysql-service"  # Example, replace with your actual DB service name
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "greenhouse_db"
            - name: DB_USER
              value: "username"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: greenhouse-ssvc
spec:
  selector:
    app: greenhouse
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: greenhouse-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greenhouse-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
