---
# PersistentVolume for MySQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data
---
# PersistentVolumeClaim for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: webapps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root  # Replace with your desired root password
            - name: MYSQL_DATABASE
              value: greenhouse
            - name: MYSQL_USER
              value: greenhouse_user
            - name: MYSQL_PASSWORD
              value: root  # Replace with your desired password
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql  # Corrected to the default MySQL data directory
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: webapps
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
# Backend Deployment with Depends On
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: raniawachene/greenhouse:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://db-service:3306/greenhouse?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "greenhouse_user"  # Corrected to match MySQL user
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
      restartPolicy: Always
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: webapps
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
