version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greenhouse
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  app-stationski:
    image: raniawachene/greenhouseback:latest
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/greenhouse?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

  frontend:
    image: raniawachene/greenhousefront:latest
    depends_on:
      - app-stationski
    restart: on-failure
    ports:
      - "4200:80"

volumes:
  db:
