version: '3.8'

services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greenhouse
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  app-stationski:
    image: raniawachene/greenhouse:latest
    depends_on:
      - mysqlDb
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqlDb:3306/greenhouse?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

volumes:
  db:
